@baseUrl = http://localhost:3000
@contentType =application/json

# @name conta
POST {{baseUrl}}/api/v1/users/authenticate HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "emanoel.vso99@gmail.com",
  "password": "123@mudar"
}


###
GET {{baseUrl}}/api/v1/users/position HTTP/1.1
Content-Type: {{contentType}}
x-access-token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDYzNGRhMGY4Y2RiM2M5NGYzMWFhYjUiLCJpYXQiOjE2MTcxMjA5NjgsImV4cCI6MTYxNzEyMjc2OH0.6vpMapXaBJNEOomc0zfkF6B3wkvnsONwlBmO4VhESn4'

{
  "email": "emanoel.vso99@gmail.com",
  "password": "123@mudar"
}

###
@idConta = {{conta.response.body.id}}
GET {{baseUrl}}/api/v1/account/{{idConta}} HTTP/1.1

###

DELETE {{baseUrl}}/api/v1/account/{{idConta}} HTTP/1.1

###
# @name categoria
POST {{baseUrl}}/api/v1/category HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "Education",
  "type": "expense"
}

###

@idCategoria = {{categoria.response.body.id}}

GET {{baseUrl}}/api/v1/category/{{idCategoria}} HTTP/1.1

###

DELETE {{baseUrl}}/api/v1/category/{{idCategoria}} HTTP/1.1

###

# CRIAÇÃO DE TRANSAÇÃO
POST {{baseUrl}}/api/v1/transaction HTTP/1.1
Content-Type: {{contentType}}

{
  "account": "5f25773b87b0232bd48ba82e",
  "category": "5f2577ab87b0232bd48ba831",
  "description": "College",
  "value": 200
}

###
GET http://localhost:3000/api/v1/report/ HTTP/1.1